### PR TITLE
LPS-88003 Add tests

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-88003

@bryceosterhaus A few things to note about this ticket:
Although I'm using `formik` to handle form states, I'm still wrapping the react component with `<aui:form>` since submitting the form with `fetch` wasn't returning the proper errors or redirects. It most likely needs backend updates and additional frontend updates to handle the errors and redirects, but to keep the existing functionality that was implemented already I left the form submission to be handled within the `<aui:form>` tag.

Do you think it's worth refactoring to use `fetch` though? There just seems to be a lot of logic around forms I'm not sure how much would really need to be re-implemented.

### CODE REVIEW

**Comment by thektan** [comment]
@epgarcia I'm creating a JSON object for the react component here if you wanted check the implementation. https://github.com/bryceosterhaus/liferay-portal/blob/bb069d7d04b210b0a6753a98e068391ad723d0e3/modules/apps/segments/segments-web/src/main/resources/META-INF/resources/edit_segments_entry.jsp#L41-L58

**Comment by thektan** [comment]
Also I'd like @andresfulla to review this ticket as well, but due to timezone differences and the urgency for this ticket, I thought it would be best for @bryceosterhaus to review the ticket first and after any necessary changes we could push it to master.

When @andresfulla makes his review I can send a new pull request with any changes.

**Comment by thektan** [comment]
@bryceosterhaus Sorry for the last minute additions. This ticket is good to review now.

**Comment by bryceosterhaus** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66145. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by bryceosterhaus** [comment]
I keep forgetting I have to forward these 🤦‍♂️

**Pull request closed without merging**
