### PR TITLE
LPS-115418 Add custom legend with checkboxes and stylish axis

### PR DESCRIPTION
**Pull request by dgarciasarai**
cc: @wincent

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by wincent** [comment]
FWIW @dgarciasarai, you can probably send this kind of PR to https://github.com/liferay-frontend/liferay-portal, and assign @bryceosterhaus (or whoever is appropriate) as reviewer. That fork is kept up-to-date by an automated script every 5 minutes, so you won't get this:

Screenshot 2020-06-24 -131252-rv0zFztE@2x

**Comment by dgarciasarai** [comment]
Thanks true @wincent!  He told me the other day but I didn't remember. Sorry. I'll resent in `liferay-frontend` repo 👍

**Comment by dgarciasarai** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/54

**Pull request closed without merging**
