### PR TITLE
LPS-111005 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-111005

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
**Testray Results Comparison**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1080854350&testrayRunIdA=1081196872&statusB=2

- [not related] - ContentPages#AddContentPage - flaky, issue seen in another run
- [not related] - ContentPages#AddContentPageFromPageTemplate - flaky virtual instance setup, LPS-106515, will be addressed by https://issues.liferay.com/browse/POSHI-63
- [fluke?] - SitesDirectory#DisplayStyleOptions - verify manually site name locator
- [fluke?] - MastersPageTemplates#CannotDeleteBlankPageTemplate - open URL error doesn't look related
- [fluke?] - CPPortalSettings#EnterReservedScreenName

**Comment by john-co** [comment]
@brianchandotcom, can you pull this branch directly? The last 3 to 4 times we ran ci:test:relevant, there weren't any related failures but we've been plagued with flukes and flaky tests.

past test runs/analysis:
https://github.com/bryceosterhaus/liferay-portal/pull/63#issuecomment-605373981
https://github.com/bryceosterhaus/liferay-portal/pull/62#issuecomment-605344078

**Comment by john-co** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@john-co @bryceosterhaus I merged this in directly.

**Comment by john-co** [comment]
**Testray Results Comparison**
https://testray.liferay.com/home/-/testray/runs/compare?formDate=1585671549106&testrayRunIdA=1081576224&testrayRunIdB=1081586211

[Unique failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1081586211&testrayRunIdA=1081576224&statusB=2)
- [Not Related] - WorkflowMetrics#ViewPendingItems - fluke?
- [Not Related] - CPReportsadmin#DeliverReportToEmail - looks flaky

[Common failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1081586211&testrayRunIdA=1081576224&statusB=3)
- [Not Related] -  DocumentsadministrationUsecase#AddDocumentTypeAndMetadata - existing regression https://issues.liferay.com/browse/LPS-111207
- [Not Related] - MastersPageTemplates#CanDuplicateMastersPageTemplate

**Pull request closed without merging**
