### PR TITLE
LPS-111005 - Update clay dependencies to latest release

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Testray import is delayed

[not related] - LocalizationWithWebContentUI#AddWCWithTranslation 
 - https://issues.liferay.com/browse/LRQA-57212
[not related] - TagsUseCase#ViewTagCloudIncrease - flaky portal instance timeout https://issues.liferay.com/browse/LPS-106515 QA to investigate stabilizing
[not related] - WebContentDisplay#AddWebContent  - same as above
[fluke?] - WorkflowDDL#EditDDLRecordViaMyWorkflowTasks - looks like a fluke, rerun the test
[not related] - WorkflowDDL#EditDDLRecordViaMyWorkflowTasks  - known issue, quarantining the test in https://github.com/wincent/liferay-portal/pull/191
[not related] - modules-unit-jdk8 - should be fixed at head, will prob need to wait until next stable run to pass to rerun test

**Comment by john-co** [comment]
pushed to https://github.com/bryceosterhaus/liferay-portal/pull/63 with quarantined/ignored tests

**Comment by john-co** [comment]
ci:close

**Pull request closed without merging**
