### PR TITLE
LPS-114946 - Update @clayui/* dependencies

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
let's try one more time!

**Comment by jbalsas** [comment]
I would manually forward this... nothing here seems to be able to cause the depot and smoke test failures that are seen there... @wincent? thoughts?

**Comment by wincent** [comment]
> thoughts?

Normally I would say, yes, do a manual forward (you'll need to do a `ci:reopen` when you create the PR on Brian's fork because the bot will close it immediately), and it's a good idea to report CI infra failures (eg. timeouts, connectivity issues, bot problems etc) to the `#ci` channel, and spurious/flaky tests to `#d-quality-assurance` on Slack.

But due to the timezone difference I figure I may as well get a head start: forwarded it [here](https://github.com/brianchandotcom/liferay-portal/pull/89690) and [reported to `#d-quality-assurance` here](https://liferay.slack.com/archives/CL84ZPHAT/p1591352870312000).

I agree with your assessment that the changes to those packages don't seem like they could cause the reported Poshi failures. If it turns out that the changes *are* the cause of a test failure, we can fast-follow with a fix.

**Pull request closed without merging**
