### PR TITLE
LPS-114162 - Update clay dependencies

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by bryceosterhaus** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
>      [exec] Execution failed for task ':apps:segments:segments-web:packageRunTest'.
>      [exec] > Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1

My money is on snapshots 😢 

I'll test this locally and push to @wincent to see if we can forward it today! :)

**Comment by jbalsas** [comment]
>  › 1 snapshot failed from 1 test suite. Inspect your code changes or re-run jest with `-u` to update them.

Jackpot!! 🤑

**Comment by jbalsas** [comment]
See https://github.com/wincent/liferay-portal/pull/288

**Comment by jbalsas** [comment]
ci:close

**Pull request closed without merging**
